### ISSUE TITLE
Can't get it to work under linux

### ISSUE THREAD

**Issue by rtega** [philippsandhaus/bafang-python#1]
Did you get this working in Linux? I can use my cable under ubuntu with virtualbox and the bafang-program. I get no reply from the unit using your code at all. It is connecting to the correct device btw.

**Comment by philippsandhaus** [comment]
If you are using the test script this will not work under linux. I have hardcoded the device name, you should adjust the code to use the corresponding device on your linux system.

**Comment by rtega** [comment]
As I said, I corrected the code since it is connecting to the correct device. It does not work though.
